"""File I/O utilities for saving and loading results."""

import numpy as np
import json
import csv
from datetime import datetime


class ResultsManager:
    """Manage saving and loading of path planning results."""
    
    @staticmethod
    def save_results(surface, toolpath, config, filename=None):
        """
        Save complete results to a JSON file.
        
        Args:
            surface: SurfaceModel instance
            toolpath: List of ToolpathPoint objects
            config: ToolpathConfig instance
            filename: Optional output filename
        
        Returns:
            Path to saved file
        """
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"data/results/results_{surface.surface_name}_{timestamp}.json"
        
        # Convert toolpath to serializable format
        toolpath_data = [pt.to_dict() for pt in toolpath]
        
        # Create results dictionary
        results = {
            'metadata': {
                'surface_name': surface.surface_name,
                'timestamp': datetime.now().isoformat(),
                'num_points': len(toolpath),
                'num_treatment_points': len([pt for pt in toolpath if not pt.is_rapid]),
                'num_rapid_points': len([pt for pt in toolpath if pt.is_rapid])
            },
            'config': {
                'standoff_distance': config.standoff_distance,
                'line_spacing': config.line_spacing,
                'feed_rate': config.feed_rate,
                'rapid_rate': config.rapid_rate,
                'use_bidirectional': config.use_bidirectional,
                'points_per_line': config.points_per_line,
                'name': config.name
            },
            'surface_bounds': {
                'min': surface.points.min(axis=0).tolist(),
                'max': surface.points.max(axis=0).tolist(),
                'center': surface.points.mean(axis=0).tolist()
            },
            'toolpath': toolpath_data,
            'surface_sample': surface.points.tolist()[:1000]  # Save subset for visualization
        }
        
        # Calculate path length
        treatment_points = [pt for pt in toolpath if not pt.is_rapid]
        length = sum(np.linalg.norm(treatment_points[i+1].position - treatment_points[i].position) 
                    for i in range(len(treatment_points)-1))
        results['metadata']['treatment_length_mm'] = float(length)
        
        # Save to JSON
        with open(filename, 'w') as f:
            json.dump(results, f, indent=2)
        
        print(f"  Results saved to: {filename}")
        return filename
    
    @staticmethod
    def load_results(filename):
        """Load results from JSON file."""
        with open(filename, 'r') as f:
            results = json.load(f)
        
        print(f"  Loaded results: {results['metadata']['surface_name']}")
        print(f"  Treatment length: {results['metadata']['treatment_length_mm']:.1f} mm")
        
        return results
    
    @staticmethod
    def export_gcode(toolpath, filename=None):
        """
        Export toolpath to G-code format.
        
        Args:
            toolpath: List of ToolpathPoint objects
            filename: Optional output filename
        
        Returns:
            Path to saved G-code file
        """
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"data/toolpaths/toolpath_{timestamp}.gcode"
        
        gcode_lines = [
            "; G-code generated by Plasma Jet Path Planner",
            "; " + datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "G90 ; Absolute positioning",
            "G21 ; Millimeter units",
            "G94 ; Units per minute feed rate",
            ""
        ]
        
        # Group points by feed rate
        current_feed = None
        
        for i, point in enumerate(toolpath):
            pos = point.position
            
            # Add feed rate command if changed
            if point.feed_rate != current_feed:
                gcode_lines.append(f"F{point.feed_rate:.1f}")
                current_feed = point.feed_rate
            
            # Add movement command
            cmd = "G0" if point.is_rapid else "G1"
            line = f"{cmd} X{pos[0]:.3f} Y{pos[1]:.3f} Z{pos[2]:.3f}"
            
            # Add comment for rapid moves
            if point.is_rapid:
                line += " ; Rapid move"
            
            gcode_lines.append(line)
        
        # End program
        gcode_lines.extend([
            "",
            "M30 ; Program end"
        ])
        
        # Write file
        with open(filename, 'w') as f:
            f.write('\n'.join(gcode_lines))
        
        print(f"  G-code exported to: {filename}")
        return filename
    
    @staticmethod
    def export_csv(toolpath, filename=None):
        """
        Export toolpath to CSV format.
        
        Args:
            toolpath: List of ToolpathPoint objects
            filename: Optional output filename
        
        Returns:
            Path to saved CSV file
        """
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"data/toolpaths/toolpath_{timestamp}.csv"
        
        with open(filename, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['X', 'Y', 'Z', 'Normal_X', 'Normal_Y', 'Normal_Z', 
                           'Feed_Rate', 'Is_Rapid'])
            
            for point in toolpath:
                writer.writerow([
                    f"{point.position[0]:.6f}",
                    f"{point.position[1]:.6f}",
                    f"{point.position[2]:.6f}",
                    f"{point.normal[0]:.6f}",
                    f"{point.normal[1]:.6f}",
                    f"{point.normal[2]:.6f}",
                    f"{point.feed_rate:.2f}",
                    str(point.is_rapid)
                ])
        
        print(f"  CSV exported to: {filename}")
        return filename

